import type { Category, Product } from "@/types/product";

export const categories: Category[] = [
  {
    id: "interieur",
    name: "Intérieur",
    description: "Plantes d'intérieur sélectionnées pour s'épanouir dans les espaces de vie.",
  },
  {
    id: "exterieur",
    name: "Extérieur",
    description: "Essences robustes pour jardins, patios et terrasses marocaines.",
  },
  {
    id: "fruitiers",
    name: "Fruitiers",
    description: "Arbres fruitiers acclimatés au soleil marocain pour jardins productifs.",
  },
  {
    id: "aromatiques",
    name: "Aromatiques",
    description: "Herbes aromatiques fraîches directement de notre pépinière d'Aghmat.",
  },
];

export const productCatalog: Product[] = [
  // ── Intérieur (25) ──────────────────────────────────────────────────────────
  {
    id: "monstera-deliciosa",
    name: "Monstera Deliciosa",
    categoryId: "interieur",
    category: "Intérieur - Ombragé",
    price: 250,
    image: { src: "/products/monstera-deliciosa.jpg", alt: "Monstera deliciosa aux grandes feuilles découpées" },
    description: "Feuilles sculptées, silhouette affirmée et croissance intérieure fiable.",
    accent: "from-[#c8d8c1] to-[#688965]",
  },
  {
    id: "ficus-lyrata",
    name: "Ficus Lyrata",
    categoryId: "interieur",
    category: "Intérieur - Lumineux",
    price: 320,
    image: { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Fiddle_Leaf_Fig_in_pot.jpg/960px-Fiddle_Leaf_Fig_in_pot.jpg", alt: "Ficus lyrata aux larges feuilles en forme de violon" },
    description: "Grand port élégant, feuilles en lyre — statement plant par excellence.",
    accent: "from-[#d4e8cf] to-[#5a7a56]",
  },
  {
    id: "pothos-dore",
    name: "Pothos Doré",
    categoryId: "interieur",
    category: "Intérieur - Ombragé",
    price: 45,
    image: { src: "/products/pothos-dore.jpg", alt: "Pothos doré aux feuilles marbréees de jaune" },
    description: "Plante débutant idéale, pousse en lumière faible et purifie l'air.",
    accent: "from-[#bfd4bf] to-[#4a6b4a]",
  },
  {
    id: "calathea-orbifolia",
    name: "Calathea Orbifolia",
    categoryId: "interieur",
    category: "Intérieur - Mi-ombre",
    price: 180,
    image: { src: "/products/calathea-orbifolia.jpg", alt: "Calathea orbifolia aux larges feuilles rayées" },
    description: "Feuilles rayées argent et vert, referme ses feuilles la nuit.",
    accent: "from-[#e0ead8] to-[#7a9a6a]",
  },
  {
    id: "sansevieria-trifasciata",
    name: "Sansevieria Trifasciata",
    categoryId: "interieur",
    category: "Intérieur - Tolérant",
    price: 95,
    image: { src: "/products/sansevieria-trifasciata.jpg", alt: "Sansevieria aux feuilles dressées panachées" },
    description: "Quasi indestructible, absorbe le CO₂ la nuit — idéale chambre à coucher.",
    accent: "from-[#c5dbc0] to-[#60875d]",
  },
  {
    id: "zamioculcas-zamiifolia",
    name: "ZZ Plant",
    categoryId: "interieur",
    category: "Intérieur - Ombragé",
    price: 120,
    image: { src: "/products/zamioculcas-zamiifolia.jpg", alt: "ZZ plant aux feuilles vernissées vert foncé" },
    description: "Feuilles luisantes, résiste à la sécheresse, parfait pour bureaux sans fenêtre.",
    accent: "from-[#c8d8c1] to-[#688965]",
  },
  {
    id: "philodendron-brasil",
    name: "Philodendron Brasil",
    categoryId: "interieur",
    category: "Intérieur - Mi-ombre",
    price: 85,
    image: { src: "/products/philodendron-brasil.jpg", alt: "Philodendron brasil aux feuilles bicolores" },
    description: "Retombant ou grimpant, feuilles bicolores vert et jaune chartreuse.",
    accent: "from-[#d4e8cf] to-[#5a7a56]",
  },
  {
    id: "dracaena-marginata",
    name: "Dracaena Marginata",
    categoryId: "interieur",
    category: "Intérieur - Lumineux",
    price: 140,
    image: { src: "/products/dracaena-marginata.jpg", alt: "Dracaena marginata aux longues feuilles rouges" },
    description: "Silhouette tropicale fine, tolère la sécheresse et l'air conditionné.",
    accent: "from-[#bfd4bf] to-[#4a6b4a]",
  },
  {
    id: "aloe-vera",
    name: "Aloe Vera",
    categoryId: "interieur",
    category: "Intérieur - Ensoleillé",
    price: 55,
    image: { src: "/products/aloe-vera.jpg", alt: "Aloe vera aux feuilles charnues vert pâle" },
    description: "Gel médicinal naturel, plante de soin aux mille usages domestiques.",
    accent: "from-[#e0ead8] to-[#7a9a6a]",
  },
  {
    id: "spathiphyllum",
    name: "Spathiphyllum",
    categoryId: "interieur",
    category: "Intérieur - Ombragé",
    price: 75,
    image: { src: "/products/spathiphyllum.jpg", alt: "Spathiphyllum aux fleurs blanches élégantes" },
    description: "Fleurs blanches en spathe, excellente purificatrice d'air intérieur.",
    accent: "from-[#c5dbc0] to-[#60875d]",
  },
  {
    id: "begonia-rex",
    name: "Begonia Rex",
    categoryId: "interieur",
    category: "Intérieur - Mi-ombre",
    price: 65,
    image: { src: "/products/begonia-rex.jpg", alt: "Begonia rex aux feuilles colorées et texturées" },
    description: "Feuilles ornementales aux motifs et couleurs spectaculaires.",
    accent: "from-[#c8d8c1] to-[#688965]",
  },
  {
    id: "chlorophytum",
    name: "Chlorophytum",
    categoryId: "interieur",
    category: "Intérieur - Tolérant",
    price: 40,
    image: { src: "/products/chlorophytum.jpg", alt: "Chlorophytum plante araignée aux longues feuilles" },
    description: "Plante araignée ultra tolérante, produit de nombreuses plantules.",
    accent: "from-[#d4e8cf] to-[#5a7a56]",
  },
  {
    id: "ficus-benjamina",
    name: "Ficus Benjamina",
    categoryId: "interieur",
    category: "Intérieur - Lumineux",
    price: 200,
    image: { src: "/products/ficus-benjamina.jpg", alt: "Ficus benjamina arbre intérieur au feuillage dense" },
    description: "Arbre d'intérieur classique, port retombant et feuilles lustrées.",
    accent: "from-[#bfd4bf] to-[#4a6b4a]",
  },
  {
    id: "croton-codiaeum",
    name: "Croton Codiaeum",
    categoryId: "interieur",
    category: "Intérieur - Ensoleillé",
    price: 110,
    image: { src: "/products/croton-codiaeum.jpg", alt: "Croton aux feuilles multicolores flamboyantes" },
    description: "Feuilles explosant de rouge, orange et jaune en pleine lumière.",
    accent: "from-[#e0ead8] to-[#7a9a6a]",
  },
  {
    id: "aglaonema-rouge",
    name: "Aglaonema Rouge",
    categoryId: "interieur",
    category: "Intérieur - Mi-ombre",
    price: 130,
    image: { src: "/products/aglaonema-rouge.jpg", alt: "Aglaonema rouge aux feuilles panachées rose et vert" },
    description: "Feuilles tachetées rouge et vert, tolère les faibles luminosités.",
    accent: "from-[#c5dbc0] to-[#60875d]",
  },
  {
    id: "anthurium-andraeanum",
    name: "Anthurium Andraeanum",
    categoryId: "interieur",
    category: "Intérieur - Lumineux",
    price: 160,
    image: { src: "/products/anthurium-andraeanum.jpg", alt: "Anthurium aux spathes lacquées rouge vif" },
    description: "Fleurs lacquées rouge vif toute l'année, symbole d'élégance tropicale.",
    accent: "from-[#c8d8c1] to-[#688965]",
  },
  {
    id: "haworthia-fasciata",
    name: "Haworthia Fasciata",
    categoryId: "interieur",
    category: "Intérieur - Ensoleillé",
    price: 50,
    image: { src: "/products/haworthia-fasciata.jpg", alt: "Haworthia fasciata petite succulente rayée blanche" },
    description: "Petite succulente graphique aux rayures blanches, arrosage mensuel.",
    accent: "from-[#d4e8cf] to-[#5a7a56]",
  },
  {
    id: "euphorbia-trigona",
    name: "Euphorbia Trigona",
    categoryId: "interieur",
    category: "Intérieur - Ensoleillé",
    price: 150,
    image: { src: "/products/euphorbia-trigona.jpg", alt: "Euphorbia trigona cactus africain triangulaire" },
    description: "Cactus africain sculptural à trois arêtes, croissance verticale rapide.",
    accent: "from-[#bfd4bf] to-[#4a6b4a]",
  },
  {
    id: "tradescantia-zebrina",
    name: "Tradescantia Zebrina",
    categoryId: "interieur",
    category: "Intérieur - Mi-ombre",
    price: 35,
    image: { src: "/products/tradescantia-zebrina.jpg", alt: "Tradescantia zebrina aux feuilles violettes zébrées" },
    description: "Retombant coloré aux reflets violet et argent, pousse très vite.",
    accent: "from-[#e0ead8] to-[#7a9a6a]",
  },
  {
    id: "peperomia-obtusifolia",
    name: "Peperomia Obtusifolia",
    categoryId: "interieur",
    category: "Intérieur - Mi-ombre",
    price: 60,
    image: { src: "/products/peperomia-obtusifolia.jpg", alt: "Peperomia obtusifolia aux feuilles rondes vernissées" },
    description: "Compact, feuilles charnues vernissées, supporte les conditions sèches.",
    accent: "from-[#c5dbc0] to-[#60875d]",
  },
  {
    id: "yucca-elephantipes",
    name: "Yucca Pied d'Éléphant",
    categoryId: "interieur",
    category: "Intérieur - Lumineux",
    price: 175,
    image: { src: "/products/yucca-elephantipes.jpg", alt: "Yucca pied d'éléphant au tronc renflé" },
    description: "Silhouette exotique au tronc renflé, supporte la sécheresse et le soleil.",
    accent: "from-[#c8d8c1] to-[#688965]",
  },
  {
    id: "dracaena-sanderiana",
    name: "Bambou de Chine",
    categoryId: "interieur",
    category: "Intérieur - Lumineux",
    price: 90,
    image: { src: "/products/dracaena-sanderiana.jpg", alt: "Bambou de chine en vase avec tiges torsadées" },
    description: "Tiges spiralées porte-bonheur, pousse dans l'eau ou substrat léger.",
    accent: "from-[#d4e8cf] to-[#5a7a56]",
  },
  {
    id: "gymnocalycium-mihanovichii",
    name: "Cactus Lune",
    categoryId: "interieur",
    category: "Intérieur - Ensoleillé",
    price: 45,
    image: { src: "/products/gymnocalycium-mihanovichii.jpg", alt: "Cactus lune greffé rose sur tige verte" },
    description: "Cactus greffé aux couleurs surprenantes, entretien quasi nul.",
    accent: "from-[#bfd4bf] to-[#4a6b4a]",
  },
  {
    id: "hoya-carnosa",
    name: "Hoya Carnosa",
    categoryId: "interieur",
    category: "Intérieur - Lumineux",
    price: 80,
    image: { src: "/products/hoya-carnosa.jpg", alt: "Hoya carnosa plante de porcelaine aux fleurs étoilées" },
    description: "Fleurs étoilées parfumées en ombelles, feuilles cireuses persistantes.",
    accent: "from-[#e0ead8] to-[#7a9a6a]",
  },
  {
    id: "calathea-makoyana",
    name: "Calathea Makoyana",
    categoryId: "interieur",
    category: "Intérieur - Mi-ombre",
    price: 195,
    image: { src: "/products/calathea-makoyana.jpg", alt: "Calathea makoyana aux feuilles translucides marbrées" },
    description: "Feuilles translucides aux motifs de plumes de paon, sensible à l'humidité.",
    accent: "from-[#c5dbc0] to-[#60875d]",
  },

  // ── Extérieur (25) ──────────────────────────────────────────────────────────
  {
    id: "olivier-ornement",
    name: "Olivier d'Ornement",
    categoryId: "exterieur",
    category: "Extérieur - Plein Soleil",
    price: 1200,
    image: { src: "/products/olivier-ornement.jpg", alt: "Olivier d'ornement au feuillage argenté" },
    description: "Silhouette méditerranéenne classique, idéale pour jardins et patios ensoleillés.",
    accent: "from-[#d7ddbf] to-[#7e8f59]",
  },
  {
    id: "bougainvillier-rose",
    name: "Bougainvillier Rose",
    categoryId: "exterieur",
    category: "Extérieur - Grimpante",
    price: 150,
    image: { src: "/products/bougainvillier-rose.jpg", alt: "Bougainvillier aux fleurs roses vibrantes" },
    description: "Fleurs exubérantes, idéal pour habiller murs et pergolas au Maroc.",
    accent: "from-[#f0cfe0] to-[#c46a8f]",
  },
  {
    id: "jasmin-etoile",
    name: "Jasmin Étoilé",
    categoryId: "exterieur",
    category: "Extérieur - Grimpante",
    price: 85,
    image: { src: "/products/jasmin-etoile.jpg", alt: "Jasmin étoilé aux petites fleurs blanches parfumées" },
    description: "Grimpant persistant au parfum envoûtant, couvre rapidement treillis et murs.",
    accent: "from-[#e8e0c5] to-[#9a8550]",
  },
  {
    id: "laurier-rose",
    name: "Laurier Rose",
    categoryId: "exterieur",
    category: "Extérieur - Plein Soleil",
    price: 120,
    image: { src: "/products/laurier-rose.jpg", alt: "Laurier rose aux fleurs roses abondantes" },
    description: "Floraison généreuse rose ou blanc, résiste à la chaleur et la sécheresse.",
    accent: "from-[#dde0c0] to-[#8a9060]",
  },
  {
    id: "hibiscus-rosa-sinensis",
    name: "Hibiscus Rosa-Sinensis",
    categoryId: "exterieur",
    category: "Extérieur - Ensoleillé",
    price: 95,
    image: { src: "/products/hibiscus-rosa-sinensis.jpg", alt: "Hibiscus aux grandes fleurs tropicales colorées" },
    description: "Grandes fleurs tropicales renouvelées chaque jour, caloriphile et généreux.",
    accent: "from-[#d5d8b5] to-[#757e42]",
  },
  {
    id: "agave-americana",
    name: "Agave Americana",
    categoryId: "exterieur",
    category: "Extérieur - Plein Soleil",
    price: 280,
    image: { src: "/products/agave-americana.jpg", alt: "Agave americana aux feuilles charnues pointues" },
    description: "Architecture végétale spectaculaire, xérophyte parfait pour jardins secs.",
    accent: "from-[#e5e8c8] to-[#8e9858]",
  },
  {
    id: "chamaerops-humilis",
    name: "Palmier Nain",
    categoryId: "exterieur",
    category: "Extérieur - Plein Soleil",
    price: 850,
    image: { src: "/products/chamaerops-humilis.jpg", alt: "Chamaerops humilis palmier nain touffu" },
    description: "Seul palmier indigène d'Europe nord-africaine, rustique et décoratif.",
    accent: "from-[#d7ddbf] to-[#7e8f59]",
  },
  {
    id: "cupressus-sempervirens",
    name: "Cyprès Méditerranéen",
    categoryId: "exterieur",
    category: "Extérieur - Plein Soleil",
    price: 650,
    image: { src: "/products/cupressus-sempervirens.jpg", alt: "Cyprès méditerranéen à la silhouette colonnaire" },
    description: "Colonne verte emblématique du paysage méditerranéen, brise-vent élégant.",
    accent: "from-[#e8e0c5] to-[#9a8550]",
  },
  {
    id: "plumbago-auriculata",
    name: "Plumbago Bleu",
    categoryId: "exterieur",
    category: "Extérieur - Ensoleillé",
    price: 75,
    image: { src: "/products/plumbago-auriculata.jpg", alt: "Plumbago bleu aux grappes de fleurs bleu azur" },
    description: "Floraison bleu azur de mai à novembre, haie fleurie légère et aérienne.",
    accent: "from-[#dde0c0] to-[#8a9060]",
  },
  {
    id: "lantana-camara",
    name: "Lantana Camara",
    categoryId: "exterieur",
    category: "Extérieur - Plein Soleil",
    price: 55,
    image: { src: "/products/lantana-camara.jpg", alt: "Lantana camara aux fleurs multicolores" },
    description: "Floraison multicolore ininterrompue, attire les papillons, supporte la chaleur.",
    accent: "from-[#d5d8b5] to-[#757e42]",
  },
  {
    id: "agapanthus-africanus",
    name: "Agapanthe Bleue",
    categoryId: "exterieur",
    category: "Extérieur - Ensoleillé",
    price: 80,
    image: { src: "/products/agapanthus-africanus.jpg", alt: "Agapanthe bleue aux ombelles bleu violet" },
    description: "Grandes ombelles bleu-violet en été, feuillage persistant architectural.",
    accent: "from-[#e5e8c8] to-[#8e9858]",
  },
  {
    id: "pittosporum-tobira",
    name: "Pittosporum Tobira",
    categoryId: "exterieur",
    category: "Extérieur - Mi-ombre",
    price: 180,
    image: { src: "/products/pittosporum-tobira.jpg", alt: "Pittosporum tobira arbuste au feuillage lustré" },
    description: "Arbuste au feuillage lustré et fleurs blanches parfumées, haie résistante.",
    accent: "from-[#d7ddbf] to-[#7e8f59]",
  },
  {
    id: "pistacia-lentiscus",
    name: "Lentisque",
    categoryId: "exterieur",
    category: "Extérieur - Plein Soleil",
    price: 350,
    image: { src: "/products/pistacia-lentiscus.jpg", alt: "Lentisque arbuste méditerranéen persistant" },
    description: "Arbuste méditerranéen indigène, baies rouges ornementales, très résistant.",
    accent: "from-[#e8e0c5] to-[#9a8550]",
  },
  {
    id: "laurus-nobilis",
    name: "Laurier Sauce",
    categoryId: "exterieur",
    category: "Extérieur - Mi-ombre",
    price: 120,
    image: { src: "/products/laurus-nobilis.jpg", alt: "Laurier sauce arbuste aux feuilles aromatiques" },
    description: "Aromatique et ornemental, taillable en topiaire ou en haie parfumée.",
    accent: "from-[#dde0c0] to-[#8a9060]",
  },
  {
    id: "rosa-grimpant",
    name: "Rosier Grimpant",
    categoryId: "exterieur",
    category: "Extérieur - Grimpante",
    price: 130,
    image: { src: "/products/rosa-grimpant.jpg", alt: "Rosier grimpant aux fleurs roses abondantes" },
    description: "Floraison remontante parfumée, habille pergolas et arches avec élégance.",
    accent: "from-[#d5d8b5] to-[#757e42]",
  },
  {
    id: "wisteria-sinensis",
    name: "Glycine de Chine",
    categoryId: "exterieur",
    category: "Extérieur - Grimpante",
    price: 200,
    image: { src: "/products/wisteria-sinensis.jpg", alt: "Glycine de chine aux longues grappes mauves" },
    description: "Grappes mauves spectaculaires en avril, parfum enivrant de jasmin.",
    accent: "from-[#e5e8c8] to-[#8e9858]",
  },
  {
    id: "punica-granatum-ornement",
    name: "Grenadier d'Ornement",
    categoryId: "exterieur",
    category: "Extérieur - Ensoleillé",
    price: 250,
    image: { src: "/products/punica-granatum-ornement.jpg", alt: "Grenadier d'ornement aux fleurs rouge orangé" },
    description: "Fleurs tubulaires rouge-orangé et petits fruits décoratifs dorés.",
    accent: "from-[#d7ddbf] to-[#7e8f59]",
  },
  {
    id: "campsis-radicans",
    name: "Bignone Orange",
    categoryId: "exterieur",
    category: "Extérieur - Grimpante",
    price: 110,
    image: { src: "/products/campsis-radicans.jpg", alt: "Bignone orange aux trompettes flamboyantes" },
    description: "Trompettes orange flamboyantes tout l'été, croissance vigoureuse.",
    accent: "from-[#e8e0c5] to-[#9a8550]",
  },
  {
    id: "photinia-red-robin",
    name: "Photinia Red Robin",
    categoryId: "exterieur",
    category: "Extérieur - Mi-ombre",
    price: 220,
    image: { src: "/products/photinia-red-robin.jpg", alt: "Photinia red robin aux jeunes pousses rouge vif" },
    description: "Nouvelles pousses rouge brillant au printemps, haie colorée et rapide.",
    accent: "from-[#dde0c0] to-[#8a9060]",
  },
  {
    id: "gazania-rigens",
    name: "Gazania",
    categoryId: "exterieur",
    category: "Extérieur - Plein Soleil",
    price: 30,
    image: { src: "/products/gazania-rigens.jpg", alt: "Gazania aux fleurs soleil jaune et orange" },
    description: "Fleurs solaires jaune-orange qui s'ouvrent à la lumière, xérophyte.",
    accent: "from-[#d5d8b5] to-[#757e42]",
  },
  {
    id: "cereus-peruvianus",
    name: "Cactus Cereus",
    categoryId: "exterieur",
    category: "Extérieur - Plein Soleil",
    price: 350,
    image: { src: "/products/cereus-peruvianus.jpg", alt: "Cactus cereus colonnaire bleuté" },
    description: "Colonne bleutée à côtes saillantes, jusqu'à 5 m, sculpture végétale vivante.",
    accent: "from-[#e5e8c8] to-[#8e9858]",
  },
  {
    id: "viburnum-tinus",
    name: "Viorne de Laurier-Tin",
    categoryId: "exterieur",
    category: "Extérieur - Mi-ombre",
    price: 190,
    image: { src: "/products/viburnum-tinus.jpg", alt: "Viburnum tinus aux fleurs blanches en cyme" },
    description: "Floraison hivernale blanche, baies bleu métallique, haie persistante dense.",
    accent: "from-[#d7ddbf] to-[#7e8f59]",
  },
  {
    id: "buxus-sempervirens",
    name: "Buis Commun",
    categoryId: "exterieur",
    category: "Extérieur - Mi-ombre",
    price: 85,
    image: { src: "/products/buxus-sempervirens.jpg", alt: "Buis commun taillé en boule" },
    description: "Topiaire classique des jardins formels, feuillage persistant dense.",
    accent: "from-[#e8e0c5] to-[#9a8550]",
  },
  {
    id: "jasminum-sambac",
    name: "Jasmin d'Arabie",
    categoryId: "exterieur",
    category: "Extérieur - Ensoleillé",
    price: 75,
    image: { src: "/products/jasminum-sambac.jpg", alt: "Jasmin d'arabie aux fleurs blanches très parfumées" },
    description: "Fleurs blanches d'une intensité parfumée unique, symbole du Maroc.",
    accent: "from-[#dde0c0] to-[#8a9060]",
  },
  {
    id: "lavandula-angustifolia",
    name: "Lavande Vraie",
    categoryId: "exterieur",
    category: "Extérieur - Plein Soleil",
    price: 50,
    image: { src: "/products/lavandula-angustifolia.jpg", alt: "Lavande vraie aux épis bleu-violet parfumés" },
    description: "Épis bleu-violet parfumés, attire les abeilles et répulse les insectes.",
    accent: "from-[#d5d8b5] to-[#757e42]",
  },

  // ── Fruitiers (25) ──────────────────────────────────────────────────────────
  {
    id: "ficus-carica",
    name: "Figuier Commun",
    categoryId: "fruitiers",
    category: "Fruitier - Méditerranéen",
    price: 380,
    image: { src: "/products/ficus-carica.jpg", alt: "Figuier commun aux larges feuilles lobées" },
    description: "Deux récoltes par an, figuier de tradition dans tous les jardins marocains.",
    accent: "from-[#f5dfc0] to-[#c4874a]",
  },
  {
    id: "citrus-sinensis",
    name: "Oranger Navel",
    categoryId: "fruitiers",
    category: "Fruitier - Agrume",
    price: 450,
    image: { src: "/products/citrus-sinensis.jpg", alt: "Oranger navel aux fruits oranges brillants" },
    description: "Oranges sans pépins juteuses, parfum de fleur d'oranger enivrant.",
    accent: "from-[#f8e8c5] to-[#d49550]",
  },
  {
    id: "citrus-limon",
    name: "Citronnier de Menton",
    categoryId: "fruitiers",
    category: "Fruitier - Agrume",
    price: 400,
    image: { src: "/products/citrus-limon.jpg", alt: "Citronnier aux citrons jaunes abondants" },
    description: "Production quasi continue, citrons généreux et feuilles aromatiques.",
    accent: "from-[#f2d8b8] to-[#b87840]",
  },
  {
    id: "citrus-reticulata",
    name: "Mandarinier",
    categoryId: "fruitiers",
    category: "Fruitier - Agrume",
    price: 420,
    image: { src: "/products/citrus-reticulata.jpg", alt: "Mandarinier aux mandarines sucrées brillantes" },
    description: "Fruits sucrés faciles à éplucher, idéal pour petits jardins et terrasses.",
    accent: "from-[#fae0c0] to-[#ca9055]",
  },
  {
    id: "persea-americana",
    name: "Avocatier",
    categoryId: "fruitiers",
    category: "Fruitier - Tropical",
    price: 550,
    image: { src: "/products/persea-americana.jpg", alt: "Avocatier aux grandes feuilles vert foncé" },
    description: "Avocats crémeux du jardin, aime la chaleur et les sols bien drainés.",
    accent: "from-[#f0d5b0] to-[#bf8035]",
  },
  {
    id: "musa-acuminata",
    name: "Bananier Nain",
    categoryId: "fruitiers",
    category: "Fruitier - Tropical",
    price: 320,
    image: { src: "/products/musa-acuminata.jpg", alt: "Bananier nain aux larges feuilles tropicales" },
    description: "Régimes de petites bananes sucrées, port compact adapté aux terrasses.",
    accent: "from-[#f5dfc0] to-[#c4874a]",
  },
  {
    id: "psidium-guajava",
    name: "Goyavier",
    categoryId: "fruitiers",
    category: "Fruitier - Tropical",
    price: 280,
    image: { src: "/products/psidium-guajava.jpg", alt: "Goyavier aux fruits ovales parfumés" },
    description: "Goyaves parfumées rose ou blanc, feuillage décoratif aux écorces colorées.",
    accent: "from-[#f8e8c5] to-[#d49550]",
  },
  {
    id: "phoenix-dactylifera",
    name: "Dattier",
    categoryId: "fruitiers",
    category: "Fruitier - Palmier",
    price: 1500,
    image: { src: "/products/phoenix-dactylifera.jpg", alt: "Palmier dattier aux longues palmes arquées" },
    description: "Emblème du Maroc, dattes mielleuses, port majestueux pour grands jardins.",
    accent: "from-[#f2d8b8] to-[#b87840]",
  },
  {
    id: "diospyros-kaki",
    name: "Kaki",
    categoryId: "fruitiers",
    category: "Fruitier - Tempéré",
    price: 480,
    image: { src: "/products/diospyros-kaki.jpg", alt: "Kakis orange brillants sur branches nues" },
    description: "Fruits orange laqués à l'automne, magnifique même sans feuilles.",
    accent: "from-[#fae0c0] to-[#ca9055]",
  },
  {
    id: "ziziphus-jujuba",
    name: "Jujubier",
    categoryId: "fruitiers",
    category: "Fruitier - Méditerranéen",
    price: 350,
    image: { src: "/products/ziziphus-jujuba.jpg", alt: "Jujubier aux petits fruits rouge-brun brillants" },
    description: "Dattes chinoises aux vertus médicinales, très résistant à la chaleur.",
    accent: "from-[#f0d5b0] to-[#bf8035]",
  },
  {
    id: "opuntia-ficus-indica",
    name: "Figuier de Barbarie",
    categoryId: "fruitiers",
    category: "Fruitier - Succulent",
    price: 90,
    image: { src: "/products/opuntia-ficus-indica.jpg", alt: "Figuier de barbarie aux raquettes épineuses" },
    description: "Figues de barbarie sucrées, emblème de l'aridité marocaine sublimée.",
    accent: "from-[#f5dfc0] to-[#c4874a]",
  },
  {
    id: "prunus-armeniaca",
    name: "Abricotier Nain",
    categoryId: "fruitiers",
    category: "Fruitier - Tempéré",
    price: 520,
    image: { src: "https://upload.wikimedia.org/wikipedia/commons/c/cd/Prunus_brigantiaca_20052002_2.JPG", alt: "Abricotier en fleurs avec petits abricots" },
    description: "Floraison printanière rose, abricots sucrés parfumés en juin.",
    accent: "from-[#f8e8c5] to-[#d49550]",
  },
  {
    id: "morus-alba",
    name: "Mûrier Blanc",
    categoryId: "fruitiers",
    category: "Fruitier - Tempéré",
    price: 460,
    image: { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Morus_alba_Tbilisi.jpg/960px-Morus_alba_Tbilisi.jpg", alt: "Mûrier blanc aux mûres blanc rosé juteuses" },
    description: "Mûres blanc-rosé généreuses, ombre appréciée dans les jardins marocains.",
    accent: "from-[#f2d8b8] to-[#b87840]",
  },
  {
    id: "cydonia-oblonga",
    name: "Cognassier",
    categoryId: "fruitiers",
    category: "Fruitier - Tempéré",
    price: 390,
    image: { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Quittenbaum_cydonia_oblonga.jpg/960px-Quittenbaum_cydonia_oblonga.jpg", alt: "Cognassier aux coings jaunes parfumés" },
    description: "Coings dorés parfumés pour confitures, fleurs roses délicates au printemps.",
    accent: "from-[#fae0c0] to-[#ca9055]",
  },
  {
    id: "eriobotrya-japonica",
    name: "Néflier du Japon",
    categoryId: "fruitiers",
    category: "Fruitier - Méditerranéen",
    price: 440,
    image: { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Loquat-0.jpg/960px-Loquat-0.jpg", alt: "Néflier du japon aux grappes de nèfles orange" },
    description: "Nèfles orange printanières et floraison hivernale parfumée unique.",
    accent: "from-[#f0d5b0] to-[#bf8035]",
  },
  {
    id: "argania-spinosa",
    name: "Arganier",
    categoryId: "fruitiers",
    category: "Fruitier - Endémique",
    price: 750,
    image: { src: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Huile_d%27argan_003.JPG/960px-Huile_d%27argan_003.JPG", alt: "Arganier emblématique du Maroc au feuillage vert" },
    description: "Trésor endémique du Maroc, noyaux précieux pour l'huile d'argan.",
    accent: "from-[#f5dfc0] to-[#c4874a]",
  },
  {
    id: "ceratonia-siliqua",
    name: "Caroubier",
    categoryId: "fruitiers",
    category: "Fruitier - Méditerranéen",
    price: 580,
    image: { src: "/products/ceratonia-siliqua.jpg", alt: "Caroubier aux longues gousses brunes" },
    description: "Gousses sucrées caroube, arbre de longue vie adapté aux sols pauvres.",
    accent: "from-[#f8e8c5] to-[#d49550]",
  },
  {
    id: "fortunella-margarita",
    name: "Kumquat",
    categoryId: "fruitiers",
    category: "Fruitier - Agrume",
    price: 350,
    image: { src: "/products/fortunella-margarita.jpg", alt: "Kumquat aux petits fruits ovales orange" },
    description: "Petits agrumes ovales que l'on mange entiers, compact en pot ou jardin.",
    accent: "from-[#f2d8b8] to-[#b87840]",
  },
  {
    id: "citrus-bergamia",
    name: "Bergamotier",
    categoryId: "fruitiers",
    category: "Fruitier - Agrume",
    price: 480,
    image: { src: "/products/citrus-bergamia.jpg", alt: "Bergamotier aux fruits verts jaunit à maturité" },
    description: "Zeste emblématique du thé Earl Grey, essence de parfumerie raffinée.",
    accent: "from-[#fae0c0] to-[#ca9055]",
  },
  {
    id: "citrus-medica",
    name: "Cédratier",
    categoryId: "fruitiers",
    category: "Fruitier - Agrume",
    price: 520,
    image: { src: "/products/citrus-medica.jpg", alt: "Cédratier aux énormes fruits bosselés jaunes" },
    description: "Fruits spectaculaires aux zestes épais très parfumés, curiosité botanique.",
    accent: "from-[#f0d5b0] to-[#bf8035]",
  },
  {
    id: "citrus-maxima",
    name: "Pamplemoussier",
    categoryId: "fruitiers",
    category: "Fruitier - Agrume",
    price: 490,
    image: { src: "/products/citrus-maxima.jpg", alt: "Pamplemoussier aux grands fruits sphériques" },
    description: "Plus grand agrume, chair rose ou blanche sucrée, arbre imposant.",
    accent: "from-[#f5dfc0] to-[#c4874a]",
  },
  {
    id: "punica-granatum",
    name: "Grenadier",
    categoryId: "fruitiers",
    category: "Fruitier - Méditerranéen",
    price: 420,
    image: { src: "/products/punica-granatum.jpg", alt: "Grenadier aux grenades rouges éclatées" },
    description: "Grenades gorgées d'arilles rubis, antioxydants naturels, très résistant.",
    accent: "from-[#f8e8c5] to-[#d49550]",
  },
  {
    id: "olea-europaea",
    name: "Olivier Productif",
    categoryId: "fruitiers",
    category: "Fruitier - Méditerranéen",
    price: 650,
    image: { src: "/products/olea-europaea.jpg", alt: "Olivier productif centenaire au feuillage argenté" },
    description: "Variété productrice d'olives noires ou vertes, arbre de mémoire et d'huile.",
    accent: "from-[#f2d8b8] to-[#b87840]",
  },
  {
    id: "carica-papaya",
    name: "Papayer Nain",
    categoryId: "fruitiers",
    category: "Fruitier - Tropical",
    price: 300,
    image: { src: "/products/carica-papaya.jpg", alt: "Papayer nain aux papayes orange au pied du tronc" },
    description: "Papayes dès la première année, saveur exotique sucrée légèrement musquée.",
    accent: "from-[#fae0c0] to-[#ca9055]",
  },
  {
    id: "vitis-vinifera",
    name: "Vigne de Table",
    categoryId: "fruitiers",
    category: "Fruitier - Tempéré",
    price: 280,
    image: { src: "/products/vitis-vinifera.jpg", alt: "Vigne de table aux grappes abondantes" },
    description: "Raisins de table sucrés, treillis naturel pour tonnelle ombragée.",
    accent: "from-[#f0d5b0] to-[#bf8035]",
  },

  // ── Aromatiques (25) ────────────────────────────────────────────────────────
  {
    id: "rosmarinus-officinalis",
    name: "Romarin Officinal",
    categoryId: "aromatiques",
    category: "Aromatique - Cuisine",
    price: 45,
    image: { src: "/products/rosmarinus-officinalis.jpg", alt: "Romarin officinal en pot de terre cuite rustique" },
    description: "Aromatique robuste aux multiples usages culinaires et médicinaux.",
    accent: "from-[#e8d8f0] to-[#8b6aad]",
  },
  {
    id: "thymus-vulgaris",
    name: "Thym Commun",
    categoryId: "aromatiques",
    category: "Aromatique - Cuisine",
    price: 35,
    image: { src: "/products/thymus-vulgaris.jpg", alt: "Thym commun en coussins fleuris lilas" },
    description: "Incontournable des cuisines méditerranéennes, antiseptique naturel puissant.",
    accent: "from-[#ddd5e8] to-[#7a5fa0]",
  },
  {
    id: "mentha-marocaine",
    name: "Menthe Marocaine",
    categoryId: "aromatiques",
    category: "Aromatique - Thé",
    price: 30,
    image: { src: "/products/mentha-marocaine.jpg", alt: "Menthe marocaine aux feuilles vert vif" },
    description: "La menthe du thé à la menthe, fraîcheur intense, incontournable au Maroc.",
    accent: "from-[#ece0f5] to-[#9475b5]",
  },
  {
    id: "ocimum-basilicum",
    name: "Basilic Vert",
    categoryId: "aromatiques",
    category: "Aromatique - Cuisine",
    price: 25,
    image: { src: "/products/ocimum-basilicum.jpg", alt: "Basilic vert aux larges feuilles brillantes" },
    description: "Parfum anisé intense, feuilles larges pour pestos et sauces fraîches.",
    accent: "from-[#e0d8ec] to-[#7865a5]",
  },
  {
    id: "salvia-officinalis",
    name: "Sauge Officinale",
    categoryId: "aromatiques",
    category: "Aromatique - Médicinal",
    price: 40,
    image: { src: "/products/salvia-officinalis.jpg", alt: "Sauge officinale aux feuilles grises veloutées" },
    description: "Feuilles grises veloutées aux propriétés digestives et antiseptiques.",
    accent: "from-[#e5daf0] to-[#8870ae]",
  },
  {
    id: "coriandrum-sativum",
    name: "Coriandre",
    categoryId: "aromatiques",
    category: "Aromatique - Cuisine",
    price: 20,
    image: { src: "/products/coriandrum-sativum.jpg", alt: "Coriandre aux fines feuilles découpées vertes" },
    description: "Herbe emblématique du tajine marocain, graines et feuilles utilisées.",
    accent: "from-[#e8d8f0] to-[#8b6aad]",
  },
  {
    id: "petroselinum-crispum",
    name: "Persil Frisé",
    categoryId: "aromatiques",
    category: "Aromatique - Cuisine",
    price: 20,
    image: { src: "/products/petroselinum-crispum.jpg", alt: "Persil frisé aux feuilles denses bouclées" },
    description: "Riche en vitamines, feuilles bouclées décoratives et culinaires.",
    accent: "from-[#ddd5e8] to-[#7a5fa0]",
  },
  {
    id: "origanum-vulgare",
    name: "Origan Méditerranéen",
    categoryId: "aromatiques",
    category: "Aromatique - Cuisine",
    price: 35,
    image: { src: "/products/origanum-vulgare.jpg", alt: "Origan méditerranéen aux petites feuilles aromatiques" },
    description: "Arôme puissant et chaud, indispensable des marinades et grillades.",
    accent: "from-[#ece0f5] to-[#9475b5]",
  },
  {
    id: "melissa-officinalis",
    name: "Mélisse Officinale",
    categoryId: "aromatiques",
    category: "Aromatique - Médicinal",
    price: 40,
    image: { src: "/products/melissa-officinalis.jpg", alt: "Mélisse officinale aux feuilles dentées citronnées" },
    description: "Parfum citronné délicat, tisane calmante pour le sommeil et la digestion.",
    accent: "from-[#e0d8ec] to-[#7865a5]",
  },
  {
    id: "lavandula-fine",
    name: "Lavande Fine",
    categoryId: "aromatiques",
    category: "Aromatique - Parfum",
    price: 45,
    image: { src: "/products/lavandula-fine.jpg", alt: "Lavande fine aux tiges fines et fleurs bleues" },
    description: "Huile essentielle la plus utilisée au monde, parfum floral et camphrée.",
    accent: "from-[#e5daf0] to-[#8870ae]",
  },
  {
    id: "anethum-graveolens",
    name: "Aneth",
    categoryId: "aromatiques",
    category: "Aromatique - Cuisine",
    price: 25,
    image: { src: "/products/anethum-graveolens.jpg", alt: "Aneth aux fines ombrelles jaunes et feuilles filiformes" },
    description: "Feuilles filiformes anisées, indispensable pour poissons et légumes.",
    accent: "from-[#e8d8f0] to-[#8b6aad]",
  },
  {
    id: "foeniculum-vulgare",
    name: "Fenouil Doux",
    categoryId: "aromatiques",
    category: "Aromatique - Cuisine",
    price: 30,
    image: { src: "/products/foeniculum-vulgare.jpg", alt: "Fenouil doux aux fines feuilles plumeuses vertes" },
    description: "Bulbe et feuilles aux saveurs anisées, diurétique naturel reconnu.",
    accent: "from-[#ddd5e8] to-[#7a5fa0]",
  },
  {
    id: "artemisia-dracunculus",
    name: "Estragon Français",
    categoryId: "aromatiques",
    category: "Aromatique - Cuisine",
    price: 45,
    image: { src: "/products/artemisia-dracunculus.jpg", alt: "Estragon français aux tiges fines dressées" },
    description: "Saveur anisée fine et complexe, star des vinaigrettes et sauces béarnaises.",
    accent: "from-[#ece0f5] to-[#9475b5]",
  },
  {
    id: "cymbopogon-citratus",
    name: "Citronnelle",
    categoryId: "aromatiques",
    category: "Aromatique - Répulsif",
    price: 50,
    image: { src: "/products/cymbopogon-citratus.jpg", alt: "Citronnelle aux longues tiges en touffe" },
    description: "Répulsif naturel contre les moustiques, base de nombreux currys asiatiques.",
    accent: "from-[#e0d8ec] to-[#7865a5]",
  },
  {
    id: "origanum-majorana",
    name: "Marjolaine Douce",
    categoryId: "aromatiques",
    category: "Aromatique - Cuisine",
    price: 35,
    image: { src: "/products/origanum-majorana.jpg", alt: "Marjolaine douce aux petites feuilles ovales grises" },
    description: "Plus douce que l'origan, parfum chaleureux pour viandes et légumes.",
    accent: "from-[#e5daf0] to-[#8870ae]",
  },
  {
    id: "pelargonium-graveolens",
    name: "Géranium Rosat",
    categoryId: "aromatiques",
    category: "Aromatique - Parfum",
    price: 55,
    image: { src: "/products/pelargonium-graveolens.jpg", alt: "Géranium rosat aux feuilles dentelées parfumées" },
    description: "Huile essentielle de rose géranium, parfum floral utilisé en cosmétique.",
    accent: "from-[#e8d8f0] to-[#8b6aad]",
  },
  {
    id: "aloysia-citrodora",
    name: "Verveine Citronnée",
    categoryId: "aromatiques",
    category: "Aromatique - Thé",
    price: 40,
    image: { src: "/products/aloysia-citrodora.jpg", alt: "Verveine citronnée aux longues feuilles lancéolées" },
    description: "Infusion citronnée digestive et apaisante, parfum de citron intense.",
    accent: "from-[#ddd5e8] to-[#7a5fa0]",
  },
  {
    id: "trigonella-foenum-graecum",
    name: "Fenugrec",
    categoryId: "aromatiques",
    category: "Aromatique - Médicinal",
    price: 25,
    image: { src: "/products/trigonella-foenum-graecum.jpg", alt: "Fenugrec aux gousses dorées et graines ambrées" },
    description: "Graines ambrées au parfum caramélisé, pilier de la cuisine et médecine marocaine.",
    accent: "from-[#ece0f5] to-[#9475b5]",
  },
  {
    id: "nigella-sativa",
    name: "Nigelle (Habbatus Sauda)",
    categoryId: "aromatiques",
    category: "Aromatique - Médicinal",
    price: 35,
    image: { src: "/products/nigella-sativa.jpg", alt: "Nigelle sativa aux fleurs bleu pâle délicates" },
    description: "Graine noire bénie citée dans les hadith, immunostimulant millénaire.",
    accent: "from-[#e0d8ec] to-[#7865a5]",
  },
  {
    id: "capparis-spinosa",
    name: "Câprier",
    categoryId: "aromatiques",
    category: "Aromatique - Cuisine",
    price: 80,
    image: { src: "/products/capparis-spinosa.jpg", alt: "Câprier aux fleurs blanches et boutons verts" },
    description: "Boutons floraux marinés au vinaigre, saveur unique des cuisines méditerranéennes.",
    accent: "from-[#e5daf0] to-[#8870ae]",
  },
  {
    id: "hyssopus-officinalis",
    name: "Hysope Officinale",
    categoryId: "aromatiques",
    category: "Aromatique - Médicinal",
    price: 40,
    image: { src: "/products/hyssopus-officinalis.jpg", alt: "Hysope officinale aux épis de fleurs bleu violet" },
    description: "Fleurs bleu-violet mellifères, expectorant naturel reconnu depuis l'Antiquité.",
    accent: "from-[#e8d8f0] to-[#8b6aad]",
  },
  {
    id: "satureja-hortensis",
    name: "Sarriette des Jardins",
    categoryId: "aromatiques",
    category: "Aromatique - Cuisine",
    price: 30,
    image: { src: "/products/satureja-hortensis.jpg", alt: "Sarriette des jardins aux petites feuilles aromatiques" },
    description: "Herbe poivrée compagne des légumineuses, antiflatulent naturel reconnu.",
    accent: "from-[#ddd5e8] to-[#7a5fa0]",
  },
  {
    id: "stevia-rebaudiana",
    name: "Stévia",
    categoryId: "aromatiques",
    category: "Aromatique - Édulcorant",
    price: 50,
    image: { src: "/products/stevia-rebaudiana.jpg", alt: "Stévia aux petites feuilles ovales vert vif" },
    description: "300 fois plus sucré que le sucre, édulcorant naturel zéro calorie.",
    accent: "from-[#ece0f5] to-[#9475b5]",
  },
  {
    id: "thymbra-spicata",
    name: "Zaatar",
    categoryId: "aromatiques",
    category: "Aromatique - Cuisine",
    price: 45,
    image: { src: "/products/thymbra-spicata.jpg", alt: "Zaatar aux petites feuilles grises aromatiques" },
    description: "Mélange d'herbes sacré du Maghreb, incontournable du petit-déjeuner marocain.",
    accent: "from-[#e0d8ec] to-[#7865a5]",
  },
  {
    id: "mentha-piperita",
    name: "Menthe Poivrée",
    categoryId: "aromatiques",
    category: "Aromatique - Thé",
    price: 30,
    image: { src: "/products/mentha-piperita.jpg", alt: "Menthe poivrée aux feuilles vert foncé dentelées" },
    description: "Fraîcheur mentholée intense, infusion digestive et tonifiante.",
    accent: "from-[#e5daf0] to-[#8870ae]",
  },
];
